## tox.toml -*- mode: toml-mode -*-
# https://tox.wiki/en/4.28.4/user_guide.html
# https://github.com/tox-dev/tox-uv
# String substitution: "{[<table>]<key>}"
requires                   = ["tox>=4", "tox-uv>=1"]
env_list                   = ["docs"]
work_dir                   = ".temp/tox/work"
temp_dir                   = ".temp/tox/temp"
skip_missing_interpreters  = false

[env_run_base]
description          = "base_env"
runner               = "uv-venv-lock-runner"
uv_sync_flags        = ["--no-editable", "--no-sources"]
allowlist_externals  = ["echo", "mkdir"]
set_env              = {}

[env.docs]
description   = "build documentation"
commands = [
  ["uv", "run", ".temp/cargo-alldocs"]
]
